package com.hztech.tools.sql;

import static com.hztech.tools.sql.DataSpaceTools.*;

import java.util.Arrays;
import java.util.List;

public class SQLTool {
	
	private static void printView(DataSpaceTools dataTool, String viewName, String sql){
		System.out.println(dataTool.buildDropedCreatViewByUnion(viewName, sql));
	}
	
	private static void print(DataSpaceTools dataTool, String sql, List<Integer> contains){
//		System.out.println(dataTool.buildSqlByUnion(sql));
		System.out.println(dataTool.buildContainsNumSqlByUnion(sql, contains));
		System.out.println();
	}
	
	private static void studentInfo(DataSpaceTools dataTool, List<Integer> contains){
		//学员信息
		String viewName = "hytline_#SPACE.V_GOVSYNTSSTUDENT";
		String sql = "SELECT T1.DEPCODE,T.\"STUID\",T.\"NAME\",T.\"SEX\",T.\"BIRTHDAY\",T.\"CARDNO\",T.\"ADDRESS\",T.\"TEMPORARYADDR\",T.\"TEMPORARYCARDNO\",T.\"NATION\",T.\"NATPLACE\",T.\"PHONE\",T.\"MAICODING\",T.\"EMAIL\",T.\"EDUCATION\",T.\"TECCLASS\",T.\"HEALTH\",T.\"PERCOAVECTYPE\",T.\"DEPNAME\",T.\"ISEFFECT\",T.\"CREUSRCODE\",T.\"CREDATE\",T.\"CRETIME\",T.\"EDIUSRCODE\",T.\"EDIDATE\",T.\"EDITIME\",T.\"DEPID\",T.\"REMARKDOC\",T.\"PHOTOPATH\",T.\"NATIONALITY\",T.\"NOWADDRESS\",T.\"LICENSETYPE\",T.\"PERDRITYPE\",T.\"SI_BOSNUM\",T.\"ORIVALIDSTARTDATE\",T.\"ORIVALIDTIMELIMIT\",T.\"ORIVALIDENDDATE\",T.\"ORIDRIVINGNUMBER\",T.\"ORIFIRSTGETLICENSEDATE\",T.\"SYSOPERTIME\",T.\"HZCUSTID\",T.\"COUNTYCODE\",T.\"NOWCOUNTYCODE\",T.\"CREDENTIALTYPE\" FROM HYTENP_#NUM.TSSTUDENT T JOIN HYTLINE_#SPACE.ENTERPRISE T1 ON T.HZCUSTID = T1.CUSTID WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
//		print(dataTool, sql, contains);
	}
	
	private static void studentApplication(DataSpaceTools dataTool, List<Integer> contains){
		//学员报名
		String viewName = "hytline_#SPACE.V_GOVSYNTSSTUAPPLICATION";
		String sql = "SELECT T1.DEPCODE, T1.CUSTID AS FK_CUSTID, T1.EPID AS FK_EPID,T.STUAPPLICATIONID,T.STUID,T.TRAININGTYPE,T.TRAININGVEHICLES,T.PERDRITYPE,T.GOVSTATUS,T.TRAFFICSTATUS,T.ADMISSIONDATE,T.BRANCHORGANCODEID,T.CERTIFICATEDATE,T.COMPLETIONNUM,T.STUDENTNUMBER,T.TSEMPLOYEEID,T.THEORYTSEMPLOYEEID,T.NEWCMCLTID,T.CONTRACTDATE,TO_CHAR(T.COLLEXAMFEES) AS COLLEXAMFEES,T.APPENDTERMS,T.TUITION,T.PAIDTUITION,T.PAYMENT,T.CHARGESID,T.REMARKDOC,T.RECTIPTNUM,T.INVOICE,T.TSSTUCLASSID,T.CLASSNO,T.ISEFFECT,T.CREUSRCODE,T.CREDATE,T.CRETIME,T.EDIUSRCODE,T.EDIDATE,T.EDITIME,T.DEPID,T.DEPNAME,T.VECID,T.BRANUM,T.BRACOLOR,T.COACHNAME,T.COACHCARDNO,T.TITNO,T.OUTOFSCHOOLREMARKDOC,T.CHANGESCHOOLREMARKDOC,T.CHANGESCHOOLNAME,T.ICCARDAPPLYSTATUS,T.PREVIOUSSTATUS,T.OLDGOVSTATUS,T.SUBJECT1HOURS,T.SUBJECT2HOURS,T.SUBJECT3HOURS,T.INTRODUCER,T.INTRODUCERPHONE,T.SUBJECTONESCROE,T.SUBJECTONESEXAMDATE,T.SUBJECTTWOSCROE,T.SUBJECTTWOSEXAMDATE,T.SUBJECTTHREESCROE,T.SUBJECTTHREESEXAMDATE,T.ICUID,T.CARDMSG,T.SENDCARDDATE,T.FINGERONETYPE,T.FINGERPOINTONE,T.FINGERTWOTYPE,T.FINGERPRINTTWO,T.SI_BOSNUM,'' AS CI_BOSNUM, '' AS ISPRINT,T.SUBJECTONESSUBUSER,T.SUBJECTONESSUBNAME,T.SUBJECTONESSUBUDATE,T.SUBJECTTWOSSUBUSER,T.SUBJECTTWOSSUBNAME,T.SUBJECTTWOSSUBUDATE,T.SUBJECTTHREESSUBUSER,T.SUBJECTTHREESSUBNAME,T.SUBJECTTHREESSUBUDATE,T.SUBJECTONESCHECKUSER,T.SUBJECTONESCHECKNAME,T.SUBJECTONESCHECKUDATE,T.SUBJECTTWOSCHECKUSER,T.SUBJECTTWOSCHECKNAME,T.SUBJECTTWOSCHECKUDATE,T.SUBJECTTHREESCHECKUSER,T.SUBJECTTHREESCHECKNAME,T.SUBJECTTHREESCHECKUDATE,T.SENDCARDUSERCODE,T.SENDCARDUSERNAME,T.CARDVALIDDATE,T.ZKEMSSTUID,T.ZKEMSSTUPWD,T.MACHINENO,T.INSURANCE,T.INSURANCEDATE,T.JJSTATUS,T.SYSOPERTIME,'' as HZCUSTID,'' as FINGERPRINT,'' as FINGERTYPE,'' as FINGERPRINTT,'' as SUBJECTFOURCHECKUDATE,'' as SUBJECTFOURCHECKNAME,'' as SUBJECTFOURCHECKUSER,'' as SUBJECTFOURSSUBUDATE,'' as SUBJECTFOURSSUBNAME,'' as SUBJECTFOURSSUBUSER,T.THEORYHOURS,T.SIMULATORHOURS,'' as GOVFLAG,T.SIMULATORHOURS2,T.TRAINING2,T.TRAINING3,T.SIMULATORHOURS3,T.TSEMPLOYEEID2,T.TSEMPLOYEEID3,T.COACHNAME2,T.COACHNAME3,T.MILEAGE2,T.MILEAGE3,T.THEORYHOURS2,T.THEORYHOURS3,T.MILEAGE1,T.TRAINING1,'' as DISABLE,'' as DISABLETIME,'' as ISOPENTIME,'' as TAGUID,T.DISTANCE_EDUCATION,T.DISTANCE_EDUCATION_AFTER,'' as REGISTEREDFACEREG,T.FACEREG,T.FACEREGURL, T.FACEREGTIME, '' as THEORYHOURSTMP FROM HYTENP_#NUM.TSSTUAPPLICATION T JOIN HYTLINE_#SPACE.ENTERPRISE T1 ON T.HZCUSTID = T1.CUSTID WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void cheakApproval(DataSpaceTools dataTool, List<Integer> contains){
		//学员报名
		String sql = "SELECT * FROM hytline_#SPACE.TSCHEAKAPPROVAL T WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void cheakApprovalDetail(DataSpaceTools dataTool, List<Integer> contains){
		//学员报名
		String sql = "SELECT * FROM hytline_#SPACE.TSCHEAKAPPROVALDETAIL T WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void studentHoursRecord(DataSpaceTools dataTool, List<Integer> contains){
		//学时记录
		String viewName = "HYTLINE_#SPACE.V_GOVSYNTSSTUHOURSRECORD";
		String sql = "SELECT T1.DEPCODE,T.\"STUHOURSRECORDID\",T.\"RECORDSEQNUM\",T.\"HOURSINSTRUMENTSNO\",T.\"STUAPPLICATIONID\",T.\"STUICNO\",T.\"COACHNAME\",T.\"TSEMPLOYEEID\",T.\"DRILLMASTERICNO\",T.\"BRANUM\",T.\"BRACOLOR\",T.\"SUBJECT\",T.\"RECORDDATE\",T.\"RECORDTIMESTART\",T.\"RECORDTIMEEND\",T.\"MILEAGE\",T.\"DRIVESTATUS\",T.\"LONGITUDE\",T.\"LATITUDE\",T.\"LEGITIMATE\",T.\"BEGINENDFLAG\",T.\"FILENAME\",T.\"CREUSRCODE\",T.\"CREDATE\",T.\"CRETIME\",T.\"EDIUSRCODE\",T.\"EDIDATE\",T.\"EDITIME\",T.\"ISEFFECT\",T.\"REMARKDOC\",T.\"CHEAKSTATUS\",T.\"EFFECTTIME\",T.\"MCSJFZ\",T.\"MTTJFS\",T.\"MTLJXS\",T.\"MINUTEDIFF\",T.\"TOTALMONEY\",T.\"RECORDDATESTART\",T.\"RECORDDATEEND\",T.\"TRAINSUBJECT\",T.\"SI_BOSNUM\",T.\"CI_BOSNUM\",T.\"ISCHECKSTR\",T.\"SYSOPERTIME\",T.\"HZCUSTID\",T.\"HOURSTYPE\",T.\"ATTENDANCE\",T.\"HOURSSTATE\",T.\"EFFECTIVETIME\",T.\"CMVECID\",T.\"GPRSMILEAGE\",T.\"COACHTAGUID\",T.\"STUTAGUID\" FROM HYTENP_#NUM.TSSTUHOURSRECORD T JOIN HYTLINE_#SPACE.ENTERPRISE T1 ON T.HZCUSTID = T1.CUSTID WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void studentHoursRecordDetail(DataSpaceTools dataTool, List<Integer> contains){
		//学时详细
		String viewName = "hytline_#SPACE.V_GOVSYNTSSTUHOURSRECORDDETAIL";
		String sql = "SELECT \"STUHOURSRECORDID\",\"RECORDSEQNUM\",\"HOURSINSTRUMENTSNO\",\"STUAPPLICATIONID\",\"STUICNO\",\"COACHNAME\",\"TSEMPLOYEEID\",\"DRILLMASTERICNO\",\"BRANUM\",\"BRACOLOR\",\"SUBJECT\",\"RECORDDATE\",\"RECORDTIMESTART\",\"RECORDTIMEEND\",\"MILEAGE\",\"DRIVESTATUS\",\"LONGITUDE\",\"LATITUDE\",\"LEGITIMATE\",\"BEGINENDFLAG\",\"FILENAME\",\"CREUSRCODE\",\"CREDATE\",\"CRETIME\",\"EDIUSRCODE\",\"EDIDATE\",\"EDITIME\",\"ISEFFECT\",\"REMARKDOC\",\"CHEAKSTATUS\",\"EFFECTTIME\",\"MCSJFZ\",\"MTTJFS\",\"MTLJXS\",\"MINUTEDIFF\",\"TOTALMONEY\",\"RECORDDATESTART\",\"RECORDDATEEND\",\"TRAINSUBJECT\",\"SI_BOSNUM\",\"CI_BOSNUM\",\"ISCHECKSTR\",\"ISZKEMCHECK\",\"SYSOPERTIME\",\"HZCUSTID\",\"ATTENDANCE\",\"HOURSTYPE\",\"HOURSSTATE\",\"EFFECTIVETIME\",\"CMVECID\",\"ISCOUNT\",\"SIGNOUTFLAG\",\"GPRSMILEAGE\",\"COACHTAGUID\",\"STUTAGUID\",\"HOURSRECORDDETAILID\" FROM HYTENP_#NUM.HOURSRECORDDETAIL T WHERE T.ISEFFECT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void faceReGist(DataSpaceTools dataTool, List<Integer> contains){
		//人脸注册记录
		String viewName = "hytline_#SPACE.V_GOVSYNFACEREGIST";
		String sql = "SELECT \"FACEREGISTID\",\"STUAPPLICATIONID\",\"REGISTDATE\",\"REGISTTIME\",\"MINIOD\",\"QUALITYTHRESHOLD\",\"CONFIDENCETHRESHOLD\",\"ISEFFECT\",\"HZCUSTID\",\"LOCATION\",\"RESULT\",\"IMGURL\",\"IMGNUM\" FROM HYTENP_#NUM.FACEREGIST T WHERE T.ISEFFECT = '0' AND T.REGISTDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void faceRecord(DataSpaceTools dataTool, List<Integer> contains){
		//人脸识别记录
		String viewName = "hytline_#SPACE.V_GOVSYNFACERECORD";
		String sql = "SELECT \"FACERECORDID\",\"STUAPPLICATIONID\",\"COMPAREDATE\",\"COMPARETIME\",\"COMPARERESULT\",\"IMAGEURL\",\"ISEFFECT\",\"EDITIME\",\"EDIDATE\",\"EDIUSRCODE\",\"CRETIME\",\"CREDATE\",\"CREUSRCODE\",\"SYSOPERTIME\",\"HZCUSTID\",\"SCORE\",\"DEVICEID\",\"FACESTATE\",\"SUBJECT\",\"STUTAGUID\",\"COACHTAGUID\",\"SIGNOUTFLAG\",\"RETRY\" FROM HYTENP_#NUM.FACERECORD T WHERE T.ISEFFECT = '0' AND T.COMPARERESULT = '0' AND T.CREDATE = '2015-05-28'";
		print(dataTool, sql, contains);
	}
	
	private static void employeeList(DataSpaceTools dataTool, List<Integer> contains){
		String sql = "SELECT TSEMPLOYEEID, NAME, SEX, BIRTHDAY, CARDNO, MOBILE, PHONE, ADDRESS, ENTRYDATE, DEPTID, STATION, EDUCATION, SPECIALTY, ARTGRADE, DUTYTITLE, OTHERSTATIONS, NATION, NATPLACE, EMAIL, MAICODING, POLITICSFACE, MARITAL, HEALTH, PHOTOID, PERID, EPID, HOMENUM, HOMEADDRESS, SOCIETYNUM, MEDICALNUM, YESORNOT, COMPACTNUM, SIGNTIME, POSITION, CONTRACTSTART, CONTRACTEND, EMPLOYEESTATUS, BRANCHORGANCODEID, WORKAGE, REMARKDOC, EMPNO, ICUID, CARDMSG, SENDCARDDATE, FINGERONETYPE, FINGERPOINTONE, FINGERTWOTYPE, FINGERPRINTTWO, CREUSRCODE, CREDATE, CRETIME, EDIUSRCODE, EDITIME, ISEFFECT, DISABLE, DISABLEDATE, DISREASON, REASON, CI_BOSNUM, CARDVALIDDATE, SERVICENUMBER, SERVICEYEARCAREFUL, SYSOPERTIME, HZCUSTID, SENDCARDDATE1, SENDCARDDATE2, SENDCARDDATE3, CARDVALIDDATE1, CARDVALIDDATE2, CARDVALIDDATE3, ISPRINT, ISPRINTTIME, TAGUID, FACEREGTIME, REGISTEREDFACEREG FROM HYTENP_#NUM.TSEMPLOYEE T WHERE T.ISEFFECT = '0'";
		print(dataTool, sql, contains);
	}
	
	private static void tscoachList(DataSpaceTools dataTool, List<Integer> contains){
		String sql = "SELECT TSCOACHID, TSEMPLOYEEID, WORSTATUS, STUTIMES, ENTYPE, STATUS, TAXLESSON, CLITNAME, PERCOAVECTYPE, GRADATE, ENDDATE, PERDRITYPE3, DRISTADATE3, WORTYPE, TITNO, LICSTATUS, ORG, TRATIMES, CHESTATUS, BEWORLEVEL, DRICARDNO3, BEWORSCOPE3, APPIXSCOPE3, DEPCODE, STARTDATE, CREUSRCODE, CREDATE, CRETIME, EDIUSRCODE, EDIDATE, EDITIME, ISEFFECT, REMARKDOC, DOCNO, SYSOPERTIME, HZCUSTID FROM HYTENP_#NUM.TSCOACH T WHERE T.ISEFFECT = '0'";
		print(dataTool, sql, contains);
	}
	
	private static void creditcltList(DataSpaceTools dataTool, List<Integer> contains){
		String sql = "SELECT * FROM HYTENP_#NUM.CREDITCLT T WHERE T.ISEFFECT = '0'";
		print(dataTool, sql, contains);
	}
	
	private static void cmvecList(DataSpaceTools dataTool, List<Integer> contains){
		String sql = "SELECT T2.EPID,'#NUM' AS CUSTID,T1.CMVECID, T1.CMCLTID, T1.MANAGERDEPCODE, T1.DEPCODE, T1.VECADDR, T1.TRAWORD, T1.AREAABBR, T1.TRANO, T1.GRADEPCODE, T1.GRADATE, T1.STADATE, T1.ENDDATE, T1.REGYPE, T1.BRACOLOR, T1.BRANUM, T1.FACTYPE, T1.MODEL, T1.VECENTYPE, T1.VECTYPE, T1.VECCOLOR, T1.ENGTYPE, T1.ENGNUM, T1.FRANUM, T1.VINNUM, T1.ELDTYPE, T1.ENGPOWER, T1.CHEPOWER, T1.SELVECSHOP, T1.PRODATE, T1.BUYDATE, T1.SETDATE, T1.WHETREAD, T1.WHEBASE, T1.TYRENUM, T1.VECLENGTH, T1.VECHIGH, T1.VECWIDE, T1.AXLNUM, T1.SPRNUM, T1.ARCSPLACE, T1.TRAMASS, T1.CREDATE, T1.CRETIME, T1.CREUSRCODE, T1.EDIDATE, T1.EDITIME, T1.EDIUSRCODE, T1.VECUPDATEDATE, T1.INITCMVECID, T1.ACTUNIT, T1.HUNMILUSEOIL, T1.DRITYPE, T1.MILAGE, T1.VECBUSSTATUS, T1.YEARS, T1.TECGRD, T1.NEXTECGRDTODATE, T1.VINNEXTDATE, T1.COLTODATE, T1.CHETODATE, T1.STACOLDATE, T1.COSSTATE, T1.TRASTATE, T1.SLITIMES, T1.VECOWENAME, T1.VECOWEPHONE, T1.BUSTYPE, T1.ISEFFECT, T1.THRINSMONEY, T1.THRINSAMOUNT, T1.THRINSNO, T1.THRINSENDDATE, T1.TRAINSMONEY, T1.TRAINSAMOUNT, T1.TRAINSNO, T1.TRAINSENDDATE, T1.FULTON, T1.FULEQUIP, T1.ARCNO, T1.BNSCOPE, T1.ISINOUT, T1.ISCOMMTOOL, T1.COMMTOOL, T1.ISLOGAPPL, T1.ISGOTOSYS, T1.LOGAPPSTAT, T1.GOTOSYSSTAT, T1.CSGUNIT, T1.ISFOREIGN, T1.ENGDISMOMENT, T1.RATROTSPEED, T1.ENGTORMOMENT, T1.ENGTORMOMROTSPEED, T1.TURFORMAT, T1.CHELODMASS, T1.TYRSTANDARD, T1.CHEPSNNUM, T1.MSTHIGSPEED, T1.WITTRAANGLE, T1.WOTTRAANGLE, T1.VINDATNUM, T1.TSMFORMAT, T1.BEFPDTFORMAT, T1.AFTPDTFORMAT, T1.FUESPOUTFORMAT, T1.BEFLAPFORMAT, T1.HYDFORMAT, T1.HAVABS, T1.INSVECCARLONG, T1.INSVECCARWIDE, T1.INSVECCARHIGH, T1.PRDFACTORY, T1.BEFWHETREAD, T1.TRANCHA, T1.BUYPRICE, T1.PRINTSIGN, T1.CHENUM, T1.COLNUM, T1.PASGRADE, T1.PASGRANEXDATE, T1.TRATIMES, T1.REPTIMES, T1.DRIVERNAME1, T1.QUANO1, T1.DRIVERNAME2, T1.QUANO2, T1.DRIVERNAME3, T1.QUANO3, T1.DRIVERNAME4, T1.QUANO4, T1.SPECVECTYPE, T1.DRIVERNAME5, T1.QUANO5, T1.ESCNAME, T1.QUANO6, T1.FRETRATYPE, T1.DANFREGRADE, T1.DAGVECCARNO, T1.CONTYPE, T1.CHECHEST, T1.POTBASE, T1.COAVECCARNO, T1.EXAMSTATUS, T1.EXAMPAYDATE, T1.VINSTATUS, T1.VINPAYDATE, T1.ECGRDSTATUS, T1.ECGRDPAYDATE, T1.COLTOPAYDATE, T1.THRINSTATUS, T1.THRINPAYDATE, T1.FILNO, T1.COADATE, T1.PASGRANESTATUS, T1.PASGRANEPAYDATE, T1.DF5, T1.REMARKS, T1.DF1, T1.DF2, T1.DF3, T1.DF4, T1.CHESEATS, T1.STOPSTARTDATE, T1.STOPENDDATE, T1.VECRESDATE, T1.CARGONAME, T1.CHASSISTYPE, T1.TANKCAPACITY, T1.CMVECBATCH, T1.CHKCMCLT, T1.CMVECUNIT, T1.BRANDNAME, T1.TRAILERTOTALMASS, T1.DOMELIGHT, T1.TXJJQ, T1.SALEAQ, T1.KXBUS, T1.BENCHMARKT, T1.BUSDJ, T1.THRINSTYPE, T1.ZYWXC, T1.TXTYPEDJ, T1.CARNUM, T1.CARPRICE, T1.EMISSIONSTANDARDS, T1.AIRCOND, T1.COIN, T1.RADIN, T1.BUSLINE, T1.FUELCHECKID, T1.SPRINTTECGRDTODATE, T1.SPRINTTECGRD, T1.TOTALMASS, T1.FUETYPE, T1.CURRENTDATEFRICREDOCDATE, T1.GRADE_CHARTER_MARK, T1.INURE_DATE, T1.EXPIRE_DATE, T1.START_POINT, T1.TSEMPLOYEEID, T1.COACHNAME, T1.TMSTATUS, T1.SYSOPERTIME, T1.USEABLE, T1.MACHINENUM, T1.ISUNIFIED FROM HYTline_#SPACE.CMVEC T1,hytenp_#NUM.enterprise t2 WHERE (t1.cmcltid = t2.cmcltid or T1.CMCLTID=T2.EPID) and T1.ISEFFECT = '0' AND (VECTYPE='70000' OR VECENTYPE='4')";
		print(dataTool, sql, contains);
	}
	
	public static void main(String[] args) {
//		--36010000
//		36042400，36048100
//		36060200
//		List<Integer> contains = Arrays.asList(50005,50006);
//		DataSpaceTools space = SPACE_3601;
//		List<Integer> contains = Arrays.asList(50124,50127);
//		DataSpaceTools space = SPACE_3604;
		List<Integer> contains = Arrays.asList(50605,50608);
		DataSpaceTools space = SPACE_3606;
		//学员信息
		studentInfo(space,contains);
		//学员报名
		studentApplication(space,contains);
		//学时记录
		studentHoursRecord(space,contains);
		//学时详细
		studentHoursRecordDetail(space,contains);
		//人脸注册记录
		faceReGist(space,contains);
		//人脸识别记录
		faceRecord(space,contains);
		//审核审批主表
		cheakApproval(space, contains);
		//审核审批细表
		cheakApprovalDetail(space, contains);
//		//教练员信息
//		employeeList(space, contains);
//		//从业信息
//		tscoachList(space, contains);
		//业户质量信誉考核信息
//		creditcltList(space, contains);
//		//车辆信息
//		cmvecList(space, contains);
		
	}
}
